
FROM eclipse-temurin:8-jdk AS build


WORKDIR /app


RUN apt-get update && apt-get install -y maven && rm -rf /var/lib/apt/lists/*


COPY pom.xml .
RUN mvn dependency:go-offline -B


COPY src ./src
RUN mvn clean package -DskipTests


FROM eclipse-temurin:8-jdk


WORKDIR /app


COPY --from=build /app/target/*.war app.war

EXPOSE 8081


ENTRYPOINT ["java", "-jar", "app.war"]
